### PR TITLE
Issue and solution suggested by @conarro for rails 5.2rc2

### PR DESCRIPTION
**Pull request by emaglio**
Issue raised by @conarro `Circular dependency detected while autoloading constant ActiveStorage::Blob::Analyzable`

- Issue due to not sorting model files before loading it
- "minitest-rails-capybara" gem has an issue with Rails 5.2rc2 so been using minitest-capybara for testing

### CODE REVIEW

**Comment by emaglio** [comment]
@seuros which branch are we using here? `master` or `v1`?

**Comment by rodrigotassinari** [comment]
I'm having the same issue `Circular dependency detected while autoloading constant ActiveStorage::Blob::Analyzable`, using Ruby v2.5.1, Rails v5.2.0.rc2 and trailblazer-rails v1.0.5

The error does not happen on my machine, but happens on Heroku.

**Comment by conarro** [comment]
@rodrigotassinari did you try the `sort` call as seen in this PR? (you can try my fork which only has that change - https://github.com/conarro/trailblazer-rails)

**Comment by rodrigotassinari** [comment]
@conarro the `.sort` call fixed the problem for me as well! But I didn't use your fork because I needed the fix on the v1 branch (since we are using Trailblazer 2.0 and not 2.1), so I used my own fork.

**Comment by conarro** [comment]
Ah gotcha. Just wanted to ensure that the fix worked for you!


On 4/2/18 at 3:32 PM, Rodrigo wrote:

@conarro <https://github.com/conarro> the .sort call fixed the problem for
me as well! But I didn't use your fork because I needed the fix on the v1
branch (since we are using Trailblazer 2.0 and not 2.1), so I used my own
fork.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/trailblazer/trailblazer-rails/pull/60#issuecomment-378019900>,
or mute the thread

**Pull request merged**
