### PR TITLE
WIP - Add Generators for core concept

### PR DESCRIPTION
**Pull request by SweeD**
Hey @apotonick,

I'm getting into Trailblazer atm and I thought it would be great to have some generators and when I read a comment of you about creating generators (can't find that comment though 😅 ) I thought let's go. 🛩 

This PR is far away from being finished but I wanted to start a discussion here about what generators would be great and since I'm not a TB pro (and 2 just got released) it would be awesome to have your thoughts about the content of the templates. 😉 

Thanks for working hard on Trailblazer, it's just awesome! <3

Cheers

### CODE REVIEW

**Comment by myabc** [comment]
hervorragend!! 

I'm not that familiar with the Rails Generator API, but I would suspect there are changes between Rails 3 + 5. In order to guarantee compatibility, we probably should write tests for the generators.

schon mal ein guter Anfang! 😄

**Comment by apotonick** [comment]
Yeah, awesome @SweeD ! We should talk with @fernandes because we originally had the idea to provide generic generators (using the thor gem, maybe) and then have bindings for Rails. That way, we can use the generators outside of Rails, with is a growing requirement for TRB.

Here's an example how to test Rails generators: https://github.com/trailblazer/cells-rails/blob/master/test/rails5.0/test/concept_generator_test.rb

Great work! :heart:

**Comment by SweeD** [comment]
Thanks for you answers. 

So do you think something like this?
```shell
$> trailblazer generate concept Thing
```

If so: How detailed should it be? 
@apotonick Maybe you could provide me how you would like to use it and what content the templates should have and I'll work on that and then change this PR to work with those? 

Cheers 🍻

**Comment by apotonick** [comment]
Well we *could* start with a very rough generator and then fine-tune the level of detail as we go? Still, @fernandes told me he got some working basic code, already?

**Comment by SweeD** [comment]
Ok great. Looking forward to @fernandes work so far. 👍

**Comment by apotonick** [comment]
@SweeD I don't see why we couldn't see what you got and then merge? Gib Gas!!!!

**Comment by SweeD** [comment]
Haha, okayokay. Let me add those tests. 😆

**Comment by fernandes** [comment]
sorry about delay here, I'm traveling with limited wifi access, I need to polish some code to push, I'm gonna try to push it until sunday, ok?

thank you for mention me here guys! 👍

**Comment by fernandes** [comment]
hey everybody!

sorry about the (long long) delay, but now, we have a game!

https://github.com/fernandes/trailblazer-generator dunno why @apotonick deleted trailblazer/trailblazer-generator repo, so after he take a look, I transfer to trb org

so, suggestions about next step?

@apotonick the gem is called trailblazer-generator and the command

`trailblazer generate operation`

what if we change to trailblazer-cli or something like that? then we have `generate` and other commands?

@SweeD feel free if you wanna call trailblazer-generator here, my idea is to provide kind of configurator to specify default output path for generated files, like:

```ruby
Trailblazer::Generator.configure do |config|
  config.output_path = Rails.root.join('app', 'concepts')
  config.loader = :explicit_singular # based on trailblazer-loader
end
```

thoughts!? :)

**Comment by fernandes** [comment]
ps: 24 days ago

shame on me 😢 thank you for your patience 😃

**Comment by seuros** [comment]
@fernandes generators should be embedded in the rails gem of each gem. `reform-rails`, `trailblaizer-rails` ect to avoid extra dependency.

**Comment by apotonick** [comment]
@seuros The main idea was to have generators without Rails dependencies, so we can use them in other frameworks, too, and then have glue code for Rails in the gems you were just naming. :wink:

**Comment by apotonick** [comment]
@fernandes That gem looks fantastic! :heart_eyes: How are we going to handle the CLI functionality, though? Great idea with using Cells for rendering the files. Should we simply start and implement some generators and then see how to make them more modular, or first discuss what features we want (e.g. what goes into `Operation` files, etc.)?

**Comment by fernandes** [comment]
@apotonick thank you bro!

the CLI functionality? using thor... it's already done... 😄 pasting the [gist](https://gist.github.com/fernandes/13bdf565cb9e66ecc3262baa8113b596) content below to make discussion easier.

```bash
$ trailblazer
Commands:
  trailblazer generate COMMANDS  # Generates trailblazer file
  trailblazer help [COMMAND]     # Describe available commands or one specific command

$ trailblazer help
Commands:
  trailblazer generate COMMANDS  # Generates trailblazer file
  trailblazer help [COMMAND]     # Describe available commands or one specific command

$ trailblazer help generate
Commands:
  trailblazer generate help [COMMAND]  # Describe subcommands or one specific subcommand
  trailblazer generate operation       # Generates trailblazer file

$ trailblazer generate     
Commands:
  trailblazer generate help [COMMAND]  # Describe subcommands or one specific subcommand
  trailblazer generate operation       # Generates trailblazer file

$ trailblazer generate help operation
Usage:
  trailblazer operation NAME

Options:
  [--steps], [--no-steps]  

Description:
  `generate operation` generate operation file

$ trailblazer generate operation     
ERROR: "trailblazer operation" was called with no arguments
Usage: "trailblazer operation NAME"

$ trailblazer generate operation Thing::Create
class Thing::Create < Trailblazer::Operation
end

$ trailblazer generate operation Thing::Create --steps
class Thing::Create < Trailblazer::Operation
  step     Model( Song, :new )
  step     :assign_current_user!
end
```

@apotonick why not everybody open issues like a `wishlist` / brainstorm on the gem repo and I organize the best way to put on the gem... after we have some functionality we discuss the modularity

personally I prefer to discuss the organization / modularity after something done, I'm not that good abstracting ( 🔮 ) future problema hahaha

that's my thoughts, I'm waiting suggestions for next steps :D

**Comment by marctich** [comment]
https://github.com/trailblazer/trailblazer-generator

**Pull request closed without merging**
