### PR TITLE
Move model related methods when Model is included only.

### PR DESCRIPTION
**Pull request by acaron**
Instead of supporting `operations.rb`, I decided to move model related methods inside `Model` module only. It must be included to access methods such as `model_name` or `to_model`.

1. `Responder` module was move inside `Model` module;
2. Autoloading was remove for `Responder` and changed for a require only;
3. Some tests were add to check that the methods are not accessible if `Model` is not include.

For `operations.rb`, a different solution must be found as discussed. And I suggest to deprecate `crud.rb`.

### CODE REVIEW

**Comment by timoschilling** [comment]
Why this change?

**Comment by acaron** [comment]
Going to repair the failed checks. I don't know why it didn't break before... Hope it is not too complicated to make the change or else I'm going to let this gem like that and start hating `Rails`.

I think that `to_model` or `model_name` shouldn't exists if you didn't include `Model`. You can't do `model` method actually so model helpers are not needed.

**Comment by timoschilling** [comment]
:+

**Comment by apotonick** [comment]
Hm, but doesn't this change just move all `Responder` code into `Model::Responder`? The `Responder` module is documented as being coupled to `Model` annieway.

Long-term I want to get rid of responders, they don't really do anything great and are very Rails-specific, which is why I wouldn't invest too much time here?! :beers:

**Comment by acaron** [comment]
If you want to get rid of them, I'll let this gem the way it is then! I'll keep @timoschilling instead (`Thing::Operations::Create`) of autoloading until the Rails case is solved!

**Pull request closed without merging**
