### PR TITLE
Extract form wrapping method

### PR DESCRIPTION
**Pull request by n-rodriguez**
This should help people to customize the returned form object from operations.
See https://github.com/trailblazer/trailblazer-rails/issues/44

### CODE REVIEW

**Comment by apotonick** [comment]
Oh wow, you're quick! :airplane:

**Comment by emaglio** [comment]
We probably have to do the same for branch `v1`

**Comment by apotonick** [comment]
Actually, I think @n-rodriguez is right and the `Rails::Form` should also respect `::model` settings from the wrapped form. Can we add this, #maybe ?

**Comment by exegete46** [comment]
Maybe it's my limited experience, but aren't underscore-methods somewhat of a "soft private"?  I'm excited for this change, because I  intend to be override `#_wrap_with_trb_form` in `ApplicationController`, and just return `form`.

Given that potential workflow, should this be given a more public, non-underscore, method name?

**Comment by apotonick** [comment]
The underscore prefix is a pattern found in monolithic objects like controllers, where way too many responsibilities are aggregated (as an example, the whole TRB-specific code should be located in a separate object, but Rails doesn't have any good injection mechanism). It means "I'm kinda private because I don't want to get in the way of your public or private code" - it's a severe code smell.

**Comment by n-rodriguez** [comment]
> it's a severe code smell.

I totaly agree

> Given that potential workflow, should this be given a more public, non-underscore, method name?

But I think we should be consistent with what we already do : to inject the `current_user` in operations we need to override the `_run_options` method in `ApplicationController` (https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails/controller.rb#L32).

**Comment by n-rodriguez** [comment]
> We probably have to do the same for branch v1

I agree as it's a no cost change in comparison with the `params:` change ;)

**Pull request merged**
