### PR TITLE
test more rubies

### PR DESCRIPTION
**Pull request by timoschilling**
`1.9` means the latest `1.9.3`
...
`2.2` means the latest `2.2.x` (`2.2.3` by today)

### CODE REVIEW

**Comment by apotonick** [comment]
I might drop 1.9 in the new Representable release because I started leveraging keyword arguments.

**Comment by apotonick** [comment]
Actually, I don't know if we need to test against all Ruby versions after 2.0 because TRB doesn't do anything specific and all the involved gems are tested against different versions. This simply delays the build with no benefits. Ideas?

**Comment by timoschilling** [comment]
Travis runs 5 builds parallel, so this don't delay the complete build. The benefit is that you can ensure that you don't use language specific thinks like `"foo-bar": 1`, which is Ruby 2.2 only for example and you ensure that every gem works with your language set, so you can't forget to drop 1.9 from trb-rails, while droping it from Representable.

But there are some other ways to speed up the builds, I think I will go truth all your gems and will optimize all travis settings.

**Comment by fernandes** [comment]
@apotonick do you care about travis build? hahaha

@timoschilling another good point of building against latest ruby is to make migration path easier (here we always build against latest)

**Comment by timoschilling** [comment]
One other reason is that it don't run on `1.9` at the moment ;)

**Pull request closed without merging**
